### ISSUE TITLE
Memory leak on capture view function

### ISSUE THREAD

**Issue by t-inamura** [SIGVerse/Client#4]
Around at the line 710 in SIGService.cpp:
```
		char *imageBuff = new char[imageSize];
		if (!m_viewsock->recvData(imageBuff, imageSize)) {
			delete [] imageBuff;
			return NULL; 
		}
		view->setBuffer(imageBuff);
```
According to the above code, member variable `m_buf`is overwritten by the `imageBuff`.
It is a cause of memory leak in SIGViewer.
Instaed of `setBuffer`, `copyBuffer` should be implemented and used. After copying the buffer, `imageBuff` in the above code should be deleted.

**Comment by tome-yamada** [comment]
Delete setBuffer function, and copyBuffer function is implemented and used.
