### ISSUE TITLE
Unnecessary history (push binary files) is kept. It should be deleted.

### ISSUE THREAD

**Issue by t-inamura** [SIGVerse/Client#6]

**Comment by t-inamura** [comment]
.gitignore file is required. Please add the suitable file.

**Comment by tome-yamada** [comment]
Added .gitignore file.
And delete unnecessary history files.
Please do git reset or rebase.

The following lists are the deleted file list and deleted folder list.
deleted files
SIGViewer/SIGViewerInstaller/SIGViewerSetup/setup.exe
SIGViewer/SIGViewer/SIGViewerInstaller/SIGViewerSetup/setup.exe
Plugin/KinectV2/KinectV2.sdf
Plugin/LeapService/LeapService.ncb
Plugin/KinectV2/Release/opencv_ffmpeg248.dll
Plugin/KinectV2/Release/log.txt
Plugin/KinectV2_Using_Quaternions/Release/log.txt

deleted folders
SIGService/Windows/boost/
SIGService/vs2008/boost/
SIGViewer/boost/
SIGViewer/OgreSDK_vc9_v1-8-0/
SIGViewer/jdk/
SIGViewer/CEGUI-0.7.6/
SIGViewer/SIGViewerInstaller/SIGViewerSetup/downloads/
SIGViewer/SIGViewer/SIGViewerInstaller/SIGViewerSetup/downloads/
SIGViewer/SIGViewer/Release/
SIGViewer/Release/
SIGViewer/SIGService_vc2008_v1-0-0/lib/Release/
SIG_Viewer/boost/
SIG_Viewer/OgreSDK_vc9_v1-8-0/
SIG_Viewer/jdk/
SIG_Viewer/CEGUI-0.7.6/
SIG_Viewer/SIGViewer/SIGViewerInstaller/SIGViewerSetup/downloads/
SIG_Viewer/SIGViewer/Release/
SIG_Viewer/SIGService_vc2008_v1-0-0/lib/Release/
